# Generated by Django 2.2 on 2020-02-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_base', '0002_auto_20200205_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
