# Generated by Django 2.2 on 2020-02-05 21:08

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('bookshop_base', '0004_auto_20200205_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
