# Generated by Django 2.2 on 2020-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_base', '0007_auto_20200206_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quanity',
            field=models.PositiveIntegerField(),
        ),
    ]
