# Generated by Django 2.2 on 2020-02-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_base', '0008_auto_20200206_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
