# Generated by Django 2.2 on 2020-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop_base', '0009_auto_20200206_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
